---
- name: Configure storm.yaml
  template: dest="{{storm_root_dir}}/apache-storm-{{storm_version}}/conf/storm.yaml" owner={{storm_user}} group={{storm_group}} mode=644 src=storm.yaml.j2
  notify:
    - Restart Supervisor

#Copy the instance specific init file
- name: Copy Debian Init File for Storm Supervisor
  template: src=init/debian/storm-supervisor.j2 dest={{supervisor_init_script}} mode=0755 force=yes
  when: ansible_os_family == 'Debian' and not use_systemd
  notify: 
    - Restart Supervisor

#Copy the instance specific init file
- name: Copy Redhat Init File for Storm Supervisor
  template: src=init/redhat/storm-supervisor.j2 dest={{supervisor_init_script}} mode=0755 force=yes
  when: ansible_os_family == 'RedHat' and not use_systemd
  notify: 
    - Restart Supervisor

#Copy the systemd specific file if systemd is installed
- name: Copy Systemd File for Storm Supervisor
  template: src=systemd/storm-supervisor.j2 dest={{supervisor_sysd_script}} mode=0644 force=yes
  when: use_systemd
  notify:
  - reload systemd configuration
  - Restart Supervisor
