---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: storm-parameters.yml
  tags:
      - always

- include: java.yml
  when: storm_java_install
  tags:
      - java

- include: stop.yml
  when: run_mode == 'Stop'

- include: install.yml
  when: not skip_install and ( run_mode == 'Install' or run_mode == 'Deploy' )

- include: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- include: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'
