# Check for mandatory parameters

- set_fact: instance_default_file={{default_file | dirname}}/{{storm_instance_name}}_{{default_file | basename}}
- set_fact: instance_init_script={{init_script | dirname }}/{{storm_instance_name}}_{{init_script | basename}}
- set_fact: conf_dir={{ storm_conf_dir }}/{{storm_instance_name}}
- set_fact: m_lock_enabled={{ storm_config['bootstrap.mlockall'] is defined and storm_config['bootstrap.mlockall'] == True }}

#Use systemd for the following distributions:
#Ubuntu 15 and up
#Debian 8 and up
#Centos 7 and up
#Relies on elasticsearch distribution installing a serviced script to determine whether one should be copied.


- set_fact: use_systemd={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution == 'CentOS' and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- set_fact: instance_sysd_script={{sysd_script | dirname }}/{{storm_instance_name}}_{{sysd_script | basename}}
  when: use_systemd
#For directories we also use the {{inventory_hostname}}-{{ storm_instance_name }} - this helps if we have a shared SAN.

- set_fact: instance_suffix={{inventory_hostname}}-{{ storm_instance_name }}
- set_fact: pid_dir={{ storm_pid_dir }}/{{instance_suffix}}
- set_fact: log_dir={{ storm_log_dir }}/{{instance_suffix}}
- set_fact: work_dir={{ storm_work_dir }}/{{instance_suffix}}
- set_fact: data_dirs={{ storm_data_dirs | append_to_list('/'+instance_suffix) }}
